version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d restaurant"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -XX:+ExitOnOutOfMemoryError
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761"]
      interval: 10s
      timeout: 3s
      retries: 12
    restart: unless-stopped

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -XX:+ExitOnOutOfMemoryError
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_URL=jdbc:postgresql://postgres:5432/restaurant
      - DB_USER=appuser
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=menu
      - RABBIT_HOST=rabbitmq
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -XX:+ExitOnOutOfMemoryError
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_URL=jdbc:postgresql://postgres:5432/restaurant
      - DB_USER=appuser
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=orders
      - RABBIT_HOST=rabbitmq
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -XX:+ExitOnOutOfMemoryError
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  kitchen-service:
    build: ./kitchen-service
    container_name: kitchen-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_URL=jdbc:postgresql://postgres:5432/restaurant
      - DB_USER=appuser
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=kitchen
      - RABBIT_HOST=rabbitmq
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -XX:+ExitOnOutOfMemoryError
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
      - RABBIT_HOST=rabbitmq
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -XX:+ExitOnOutOfMemoryError
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
      - RABBIT_HOST=rabbitmq
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx128m -XX:+ExitOnOutOfMemoryError
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
