server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/menu/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: kitchen-service
          uri: lb://kitchen-service
          predicates:
            - Path=/kitchen/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
