server:
  port: 8082  

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:order-db
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.amqp: DEBUG
