name: CI (build / test / compose)

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Build & Test – ${{ matrix.svc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        svc:
          - eureka-server
          - gateway-service
          - menu-service
          - order-service
          - kitchen-service
          - delivery-service
          - notification-service
    defaults:
      run:
        working-directory: ${{ matrix.svc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Maven build & test (policy by branch)
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            mvn -q -DskipITs=false test
          else
            mvn -q -DskipITs=true  test
          fi

  compose_smoke:
    name: Compose smoke test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start dependencies only (db + mq)
        run: docker compose up -d postgres rabbitmq

      - name: Build all services (dev/demo)
        run: docker compose build

      - name: Run stack
        run: |
          docker compose up -d
          sleep 30

      - name: Healthcheck
        run: |
          (curl -fsS http://localhost:8080/actuator/health || curl -fsS http://localhost:8080/) \
          && echo "Gateway OK"
          curl -fsS http://localhost:8081/actuator/health || true

      - name: Cleanup
        if: always()
        run: docker compose down
